from .add_local_registry import AddLocalRegistry
from .add_remote_registry import AddRemoteRegistry
from .ask_option import AskOption
from .change_env_manager import ChangeEnvManager
from .change_python_version import ChangePythonVersion
from .change_template_version_policy import ChangeTemplateVersionPolicy
from .new_template import NewTemplate
from .new_template2 import NewTemplate2
from .new_template3 import NewTemplate3
from .perform_action import PerformAction
from .remove_registry import RemoveRegistry
from .restore_default_registry import RestoreDefaultRegistry
from .restore_defaults import RestoreDefaults
from .update_conda import UpdateConda
