from .ask_option import AskOption
from .perform_action import PerformAction
from .change_python_version import ChangePythonVersion
from .new_template import NewTemplate
from .change_env_manager import ChangeEnvManager
from .restore_defaults import RestoreDefaults
from .restore_default_registry import RestoreDefaultRegistry
from .add_remote_registry import AddRemoteRegistry
from .add_local_registry import AddLocalRegistry
from .remove_registry import RemoveRegistry
from .update_conda import UpdateConda
from .change_template_version_policy import ChangeTemplateVersionPolicy
